### ISSUE TITLE
Support for 12 hour time

### ISSUE THREAD

**Issue by mattyrc** [nikitabobko/gcal-notifier-kotlin-gtk#10]
Currently the calendar times are all shown in 24 hour format. It would be great to have an option to also show 12 hour time format. Possibly through a command line flag such as '--twelve-hour' ?

Also wanted to say thanks for sharing this app.

**Comment by nikitabobko** [comment]
In upcoming 2.0.8 version I added possibility to specify date and time format. Refer to format documentation here: https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/text/SimpleDateFormat.html

(12-hour format would stand as "K:mm a")

Configuration done via manual editing `yml` configuration file. To open this file click new `Settings` item in popup.

Cheers :)

**Comment by nikitabobko** [comment]
Please keep in mind that app relaunch is required after editing settings file
