### ISSUE TITLE
Fails to start:  Class::class.java.getRes…eAsStream("/version.txt") must not be null

### ISSUE THREAD

**Issue by andreas-ebot7** [nikitabobko/gcal-notifier-kotlin-gtk#9]
`gcal-notifier-kotlin-gtk-2.0.6-1` fails to start on my system. Installed from `aur` with `yay -S gcal-notifier-kotlin-gtk`

### Issue

```
gcal-notifier-kotlin-gtk
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: Class::class.java.getRes…eAsStream("/version.txt") must not be null
        at ru.nikitabobko.gcalnotifier.MainKt.<clinit>(Main.kt:10)
```

### System

![image](https://user-images.githubusercontent.com/59447501/73651316-79202a80-4684-11ea-9b8e-6e34a5960fd8.png)

**Comment by nikitabobko** [comment]
Thanks for contributing!

Unfortunately, I cannot reproduce the problem. I run Manjaro 18.1.15 in VirtualBox and tried to install `gcal-notifier` in Live CD. Everything had gone smoothly:
![1](https://user-images.githubusercontent.com/20517828/73656526-5ea87a00-46a1-11ea-855e-ed9480be4136.png)

What is output of `java -version` on your system?

**Comment by andreas-ebot7** [comment]
```
java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10)
OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
```
Thanks for looking into it. Same error with `pamac`. The installation seems to work. Probably an issue with path or expected location of the file.

**Comment by nikitabobko** [comment]
Fun. On Java 8 everything is ok. On Java 11 I got exception you provided. Thank you one more time. I will fix it.

**Comment by andreas-ebot7** [comment]
Thanks. Confirming it's fixed! 🥳
